package com.hamraj37.devpulse.ui.theme

import androidx.compose.ui.graphics.Color

// Active Badge Palette (Status Indicators)
val ActiveBadge = Color(0xFF388E3C)

// Red Theme Palette
val RedPrimaryLight = Color(0xFFB3261E)
val RedOnPrimaryLight = Color(0xFFFFFFFF)
val RedPrimaryContainerLight = Color(0xFFF9DEDC)
val RedOnPrimaryContainerLight = Color(0xFF410E0B)
val RedSecondaryLight = Color(0xFF775652)
val RedSecondaryContainerLight = Color(0xFFFFDAD6)
val RedOnSecondaryContainerLight = Color(0xFF2C1512)
val RedTertiaryLight = Color(0xFF705C2E)
val RedBackgroundLight = Color(0xFFFFF8F7)
val RedSurfaceLight = Color(0xFFFFFFFF)
val RedSurfaceVariantLight = Color(0xFFF4DEDC)
val RedSurfaceCardLight = Color(0xFFFFF0EE)

val RedPrimaryDark = Color(0xFFF2B8B5)
val RedOnPrimaryDark = Color(0xFF601410)
val RedPrimaryContainerDark = Color(0xFF8C1D18)
val RedOnPrimaryContainerDark = Color(0xFFF9DEDC)
val RedSecondaryDark = Color(0xFFE6BDD8)
val RedSecondaryContainerDark = Color(0xFF5D3F3B)
val RedOnSecondaryContainerDark = Color(0xFFFFDAD6)
val RedTertiaryDark = Color(0xFFDFC28C)
val RedBackgroundDark = Color(0xFF1A1110)
val RedSurfaceDark = Color(0xFF201A19)
val RedSurfaceVariantDark = Color(0xFF3D3230)
val RedBannerDark = Color(0xFF281E1D)
val RedChipBgDark = Color(0xFF332827)

// Blue Theme Palette
val BluePrimaryLight = Color(0xFF1B62B2)
val BlueOnPrimaryLight = Color(0xFFFFFFFF)
val BluePrimaryContainerLight = Color(0xFFD6E3FF)
val BlueOnPrimaryContainerLight = Color(0xFF001B3D)
val BlueSecondaryLight = Color(0xFF535F70)
val BlueSecondaryContainerLight = Color(0xFFD7E3F7)
val BlueOnSecondaryContainerLight = Color(0xFF101C2B)
val BlueTertiaryLight = Color(0xFF6B5778)
val BlueBackgroundLight = Color(0xFFF8F9FF)
val BlueSurfaceLight = Color(0xFFFFFFFF)
val BlueSurfaceVariantLight = Color(0xFFE0E2EC)
val BlueSurfaceCardLight = Color(0xFFF2F5FF)

val BluePrimaryDark = Color(0xFFA8C8FF)
val BlueOnPrimaryDark = Color(0xFF003062)
val BluePrimaryContainerDark = Color(0xFF004689)
val BlueOnPrimaryContainerDark = Color(0xFFD6E3FF)
val BlueSecondaryDark = Color(0xFFBBBEC6)
val BlueSecondaryContainerDark = Color(0xFF3B4758)
val BlueOnSecondaryContainerDark = Color(0xFFD7E3F7)
val BlueTertiaryDark = Color(0xFFD7BEE4)
val BlueBackgroundDark = Color(0xFF111318)
val BlueSurfaceDark = Color(0xFF191C20)
val BlueSurfaceVariantDark = Color(0xFF32353A)
val BlueBannerDark = Color(0xFF1E2228)
val BlueChipBgDark = Color(0xFF282D35)

// Green Theme Palette
val GreenPrimaryLight = Color(0xFF2D6A4F)
val GreenOnPrimaryLight = Color(0xFFFFFFFF)
val GreenPrimaryContainerLight = Color(0xFFB7F0D0)
val GreenOnPrimaryContainerLight = Color(0xFF002113)
val GreenSecondaryLight = Color(0xFF4D6356)
val GreenSecondaryContainerLight = Color(0xFFCFE9D7)
val GreenOnSecondaryContainerLight = Color(0xFF0B1F15)
val GreenTertiaryLight = Color(0xFF3D6373)
val GreenBackgroundLight = Color(0xFFF5FBF6)
val GreenSurfaceLight = Color(0xFFFFFFFF)
val GreenSurfaceVariantLight = Color(0xFFE0EFE5)
val GreenSurfaceCardLight = Color(0xFFEFF9F2)

val GreenPrimaryDark = Color(0xFF9CD4B5)
val GreenOnPrimaryDark = Color(0xFF003822)
val GreenPrimaryContainerDark = Color(0xFF115138)
val GreenOnPrimaryContainerDark = Color(0xFFB7F0D0)
val GreenSecondaryDark = Color(0xFFB3CCBC)
val GreenSecondaryContainerDark = Color(0xFF354B3F)
val GreenOnSecondaryContainerDark = Color(0xFFCFE9D7)
val GreenTertiaryDark = Color(0xFFA5CCE0)
val GreenBackgroundDark = Color(0xFF0F1511)
val GreenSurfaceDark = Color(0xFF171D19)
val GreenSurfaceVariantDark = Color(0xFF252C27)
val GreenBannerDark = Color(0xFF1A221C)
val GreenChipBgDark = Color(0xFF242E27)

// Yellow Theme Palette
val YellowPrimaryLight = Color(0xFF755B00)
val YellowOnPrimaryLight = Color(0xFFFFFFFF)
val YellowPrimaryContainerLight = Color(0xFFFFDF93)
val YellowOnPrimaryContainerLight = Color(0xFF241A00)
val YellowSecondaryLight = Color(0xFF685D3F)
val YellowSecondaryContainerLight = Color(0xFFF1E1BB)
val YellowOnSecondaryContainerLight = Color(0xFF221A04)
val YellowTertiaryLight = Color(0xFF47664A)
val YellowBackgroundLight = Color(0xFFFFFDF7)
val YellowSurfaceLight = Color(0xFFFFFFFF)
val YellowSurfaceVariantLight = Color(0xFFEAE2CD)
val YellowSurfaceCardLight = Color(0xFFFCF8E9)

val YellowPrimaryDark = Color(0xFFEABC4B)
val YellowOnPrimaryDark = Color(0xFF3E2E00)
val YellowPrimaryContainerDark = Color(0xFF594400)
val YellowOnPrimaryContainerDark = Color(0xFFFFDF93)
val YellowSecondaryDark = Color(0xFFD4C5A1)
val YellowSecondaryContainerDark = Color(0xFF50462A)
val YellowOnSecondaryContainerDark = Color(0xFFF1E1BB)
val YellowTertiaryDark = Color(0xFFADCFAC)
val YellowBackgroundDark = Color(0xFF16130C)
val YellowSurfaceDark = Color(0xFF1E1B13)
val YellowSurfaceVariantDark = Color(0xFF2D2A21)
val YellowBannerDark = Color(0xFF231F16)
val YellowChipBgDark = Color(0xFF2E291C)
